### ISSUE TITLE
User experience improvements

### ISSUE THREAD

**Issue by ravisuhag** [odpf/guardian#103]
**Is your feature request related to a problem? Please describe.**
In some places, user experience can be improved to show better messages. 

**Describe the solution you'd like**

- Add init command for a policy and provider
- Print better blank state errors - no resource found. 
- Show spinner when fetching results in commands (with tty)

**Comment by ishanarya0** [comment]
@ravisuhag The init command needs to generate a generic template for policy or provider?

Command: `guardian provider/policy init --name=<file-name>`

**Comment by ishanarya0** [comment]
@ravisuhag Can we go by this generic initialization? [Link](https://github.com/odpf/guardian/commit/101f9ddec98a53b4cc2db9e74d09cb842c966d36)

**Comment by ravisuhag** [comment]
@ishanarya0 yes, but let pull the templates folder out of cmd.

**Comment by rahmatrhd** [comment]
wanted to discuss this here as well, about how we should pass `id` in commands. In some `view` commands we are passing `id` as an argument while in others (`edit`, `appeal revoke`, etc.) we are using `--id` flag.

Can we standardize all commands to pick `id` from args? so it'll look like these:
```diff
- guardian provider edit --id=1234 --file=./provider.yaml
+ guardian provider edit 1234 --file=./provider.yaml

- guardian appeal revoke --id=1234 --reason=""
+ guardian appeal revoke 1234 --reason=""

etc.
```

**Comment by ishanarya0** [comment]
> wanted to discuss this here as well, about how we should pass `id` in commands. In some `view` commands we are passing `id` as an argument while in others (`edit`, `appeal revoke`, etc.) we are using `--id` flag.
> 
> Can we standardize all commands to pick `id` from args? so it'll look like these:
> 
> ```diff
> - guardian provider edit --id=1234 --file=./provider.yaml
> + guardian provider edit 1234 --file=./provider.yaml
> 
> - guardian appeal revoke --id=1234 --reason=""
> + guardian appeal revoke 1234 --reason=""
> 
> etc.
> ```

Yes, that looks better! I'll do the changes.
