### ISSUE TITLE
Metabase failed to parse databases from /api/database

### ISSUE THREAD

**Issue by singhvikash11** [odpf/guardian#136]
**Describe the bug**
The [struct](https://github.com/odpf/guardian/blob/main/plugins/providers/metabase/resource.go#L15) mapped to Metabase list database API response is invalid. It needs to be changed to:
```
type DatabaseResponse struct {
	Data []*Database `json:"data"`
}
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Metabase providers with databases
2. See an error in the log

**Expected behaviour**
It should be able to parse databases and add these databases as resources in Guardian

**Comment by rahmatrhd** [comment]
@singhvikash11 which metabase version did you use?

**Comment by singhvikash11** [comment]
@rahmatrhd I am using the metabase version v0.42.0

**Comment by rahmatrhd** [comment]
fixed by https://github.com/odpf/guardian/pull/157
