### ISSUE TITLE
Policy update failed if its not for latest version

### ISSUE THREAD

**Issue by singhvikash11** [odpf/guardian#149]
**Describe the bug**
Guardian provides PUT API to update existing policy. But it's falling when the payload of policy has a version in it and that version is not the latest.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a policy
2. Update the policy with version 1
3. Update the policy with version 1 

**Expected behaviour**
Either policy should be updated and create a new version instead of input-version, or it'll throw an error the policy is not the latest one so it'll not update.

**Comment by rahmatrhd** [comment]
https://github.com/odpf/guardian/blob/main/core/policy/service.go#L141

need to make changes as following to make sure on update we're always updating based on the latest version.

```diff
-	latestPolicy, err := s.GetOne(p.ID, p.Version)
+	latestPolicy, err := s.GetOne(p.ID, 0)
```
(`Version=0` will return the latest policy)

@singhvikash11 would you be able to work on the changes, mas?

**Comment by rahmatrhd** [comment]
fixed in https://github.com/odpf/guardian/pull/166
