### ISSUE TITLE
override approvers in policy if resource has approvers defined

### ISSUE THREAD

**Issue by bsushmith** [odpf/guardian#151]
**Is your feature request related to a problem? Please describe.**
The approvers in the provider files are at provider level and would be applicable to all resources for that provider.
But if we need an different approver in the same provider for one or two particular resources, we use the details column in the resources table to add specific approver for that resource only.

Whenever a new resource(dataset) gets added, the details is empty. and we have to manually populate the details column. and till the time details is populated, if an appeal is raised against such a resource - the guardian app panics and crashes.

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 80 [running]:
reflect.Value.Type({0x0, 0x0, 0x133b74b})
  /opt/hostedtoolcache/go/1.17.7/x64/src/reflect/value.go:2262 +0x12e
github.com/odpf/guardian/core/appeal.(*Service).resolveApprovers(0xc0004b02d0, {0xc00053dfc0, 0x1, 0xc0013276c0}, 0xc001e6d9b0)
  /home/runner/work/guardian/guardian/core/appeal/service.go:500 +0x3e6
github.com/odpf/guardian/core/appeal.(*Service).fillApprovals(0xc0004b02d0, 0xc0005aaa00, 0xc000cc5860)
```

**Describe the solution you'd like**
Would like to have a way to override approvers in policy definition itself, in a way such as even if the details column is empty/nil. then the approvers are taken from the policy file itself.

**Comment by rahmatrhd** [comment]
> Would like to have a way to override approvers in policy definition itself, in a way such as even if the details column is empty/nil. then the approvers are taken from the policy file itself.

I think this is possible since expression is supported in the `approvers` field in policy. We just need to write conditions as such.

> Whenever a new resource(dataset) gets added, the details is empty.

Anyway, I think this is still need to be fixed. We should merge the existing resource details & new resource details

**Comment by aok1j1** [comment]
> I think this is possible since expression is supported in the approvers field in policy. We just need to write conditions as such.

Yes. In the end, the solution that we implemented for our policy definitions was done in this way only. 

```
approvers:
      - '$appeal.resource.details == nil ? ["data-owner@abc.com"] : $appeal.resource.details.owner'
```

**Comment by bsushmith** [comment]
> I think this is possible since expression is supported in the approvers field in policy. We just need to write conditions as such.

Yes. In the end, the solution that we implemented for our policy definitions was done in this way only.

```
approvers:
      - '$appeal.resource.details == nil ? ["data-owner@abc.com"] : $appeal.resource.details.owner'
```
