### ISSUE TITLE
Add a method to delete providers and its corresponding resources

### ISSUE THREAD

**Issue by bsushmith** [odpf/guardian#154]
Request for a feature to delete providers and its corresponding resources from guardian. 

Currently, if a provider was added to guardian, then guardian automatically fetches the resources and populates the resources table. If in case, the provider and its resources should not be there in guardian at all and there are no appeals tied up with this provider, the only way to remove them would be to run a query on the guardian db directly since there are no api's implemented in guardian for removing providers.

**Comment by mabdh** [comment]
@bsushmith for the issue, I think better to follow the issue template for [feature request](https://github.com/odpf/guardian/blob/main/.github/ISSUE_TEMPLATE/feature_request.md) 
can you please updating it?
