### ISSUE TITLE
API to fetch different provider types

### ISSUE THREAD

**Issue by bsushmith** [odpf/guardian#158]
### Feature request:

An API to fetch different provider types registered/present in guardian. 

### Reason:
Currently, when guardian api is integrated with a UI to enable & onboard the users for appeal creation, with the api's provided by guardian, all the resources of all providers would be available at once for the user to filter out and select what he/she would want to appeal for. 

With a single kind of provider registered, this doesn't pose much of a problem. But with different kinds of additional providers registered like - bigquery, metabase, tableau, etc., it gets confusing super quick from user perspective to select. 

With this API, the UI would be able to give options to user what type of provider access they are requesting for at a very high level. and in turn filtering the resources to show only the particular provider ones.

**Comment by rahmatrhd** [comment]
@bsushmith `provider_type` and `provider_urn` are already supported in list resources API, please check

**Comment by bsushmith** [comment]
Adding details from discussion in odpf slack here - 

**Details**:
We are using this UI (screenshot) on top of guardian to have a smooth flow for the user raising an appeal.(fields in green are new ones based on requested changes in guardian)

Currently, with the api’s provided by guardian, all the resources of all providers would be available at once for the user to filter out and select what he/she would want to appeal for.
With a single kind of provider registered, this does not pose much of a problem. But with different kinds of additional providers registered like - bigquery, metabase, tableau, etc., it gets confusing super quick from user perspective to select.

**Changes**:
We plan to add two new drop downs in the appeal request page UI - ProviderType &  ResourceType (green shaded boxes).
These changes will provide clear flow of appeals process for users for whichever resource they request for , say bigquery_dataset or metabase-group.

To enable providerType/ResourceType filtering in UI -
We plan to add a guardian API which would fetch current existing provider/resourceTypes.

![Screenshot 2022-04-14 at 14 13 11](https://user-images.githubusercontent.com/6890568/163805867-a0f468ca-00ba-4818-8db7-b697ebe58e93.png)
