### ISSUE TITLE
Bulk appeal access revocation

### ISSUE THREAD

**Issue by singhvikash11** [odpf/guardian#202]
**Summary**
Guardian does not consider the user status like quit, inactive etc in org/company, there is a possibility that users can switch org while they still have active appeals in the system. These accounts pose a huge security threat. When they grow in number, they also become unmanageable for IT administrators. Hence it is essential to periodically check for inactive user accounts and take appropriate actions on them as soon as they're identified.

**Proposed solution**
Guardian appeal-approval workflow takes identity providers(IAM) like Shied, Ldap, and HTTP to fetch user details like name, title, manager, department, etc.  
As a solution we are proposing the following steps:

- Identity providers to have a user status as metadata like `accountStatus=active`
- a scheduled job in Guardian 
    - To fetch all users having active appeals
    - fetch the status of a user using IAM 
    - revoke appeal access if a user is not active

**Additional context**
In the future, we want to trace whether a user is idle for more than a configured duration and will mark a user as inactive and revoke its access.

**Comment by ravisuhag** [comment]
@singhvikash11 Are we expecting that Guardian will expect `accountStatus` key to be there in identity manager? I think this should be kept flexible and there could be mapping that can de be defined to figure out which key to look for. Thoughts?

**Comment by singhvikash11** [comment]
@ravisuhag yes, we'll make it flexible. Users can map `accountStatus` in `IAMSchema`, for now we are not creating any expression to evaluate the status of user.

**Comment by ravisuhag** [comment]
@rahmatrhd @singhvikash11 Based on the discussion on the PR. I have a few questions?

Since IAM is registered in policy, the account status config can change based on each policy. 
- How do we expect the IAM provider to check for it for each policy registered in a generic way? 
- Would dormant access revocation happen at the policy level? 
- Will the job check status config for each policy and then revoke access for users?

**Comment by singhvikash11** [comment]
@ravisuhag IMO, this is as part of the access-request lifecycle in a broader way. Here as a lifecycle of the access request, it filters all the active appeals and kicks-in revocation stage if the user of these appeals becomes `inactive` based on a policy configured.

**Comment by ravisuhag** [comment]
Few thoughts:

1. I think most of the logic should be contained within Job only. We should avoid making changes in core for this apart from introducing status which can be configured in IAM config. 
2. If such actions increase more and more we should think of a way to make jobs generic. On possible way could be. Job can be defined in a yaml config. 

```
action: appeal.revoke 
when: 
on: 
```

**Comment by rahmatrhd** [comment]
@singhvikash11 just had a thought, for all current policies, they still don't have the account status configured, then how we will revoke active appeals attached to those policies? The same case also for if the iam config got updated due to the contract changes with the identity service.

Seems we can't have this process as part of the policy iam. Agree with @ravisuhag that the logic should be part of the job only.

**Comment by ravisuhag** [comment]
Update:
Guardian will provide an API to revoke access to all resources for a given user. The decision of the dormant users can be taken outside of Guardian and access can be revoked using the bulk access revocation API.

**Comment by singhvikash11** [comment]
@rahmatrhd @ravisuhag as we discussed we'll create an API to revoke appeals in bulk based on appeal filter criteria. Please lemme know if the below contract is okay for this Api.

> message RevokeAppealsRequest {
  string account_id = 1;
  repeated string statuses = 2;
  repeated string role = 3;
  repeated string provider_types = 4;
  repeated string provider_urns = 5;
  repeated string resource_types = 6;
  repeated string resource_urns = 7;
  string created_by = 8;
  message Reason {
    string reason = 1;
  }
  Reason reason = 9;
}

> message RevokeAppealsResponse {
  repeated Appeal appeal = 1;
}


> rpc RevokeAppeals(RevokeAppealsRequest) returns (RevokeAppealsResponse) {
        option (google.api.http) = {
          post: "/v1beta1/appeals/revoke"
          body: "reason"
        };
    }
