### ISSUE TITLE
The details column for a resource is not getting updated as part of the fetch_resources cron job.

### ISSUE THREAD

**Issue by singhvikash11** [odpf/guardian#208]
**Description**
The `details` column for a resource is not getting updated as part of the `fetch_resources` cron job.

**To Reproduce**
Run the `fetch_resources` cron job and it will not update the` details` columns

**Expected behaviour**
The `fetch_resources` cron job should update the `details` column.

**Comment by rahmatrhd** [comment]
@singhvikash11  was fetch_resources job adds any information into `details` previously?
