### ISSUE TITLE
Allow provider to configure access duration

### ISSUE THREAD

**Issue by singhvikash11** [odpf/guardian#213]
**Summary**
Currently, we can't configure the request duration in the provider. The request duration option is defined by the users on the frontend side and every provider has the same duration option like 1 day, 3 days, 30 days, permanent etc

**Proposed solution**
Change provider config to take request duration while registering a provider.

**Comment by ravisuhag** [comment]
@singhvikash11 Any reason this should be part of the provider and not policy?

**Comment by singhvikash11** [comment]
@ravisuhag request duration needs to be given as payload while creating appeal. Policy kick in after an appeal is created to generate the approval flow. Another reason is that the same policy can be associated with multiple providers of the same type.

**Comment by ravisuhag** [comment]
So default values will be defined when the user is registering a new provider?

@rahmatrhd your thoughts on it?

**Comment by rahmatrhd** [comment]
IMO we should move any appeal-related configurations to the policy, while the provider should only care about resource-related stuff. At least that should be the scope for policy and provider. For example, the current [AppealConfig](https://odpf.github.io/guardian/docs/reference/provider#appealconfig) in the provider should be part of the policy (we can create an issue for this), as well as this predefined duration options. In the provider, we can have configurations such as filtering resources, adding default metadata, or anything else related to the resources

---

> @singhvikash11: Policy kick in after an appeal is created to generate the approval flow. 

Yes, but we also can fetch the policy details once the resource is selected because policy is associated with a resource type

**Comment by ravisuhag** [comment]
@rahmatrhd +1 to this. Sounds like a good idea. @singhvikash11 WDYT? If we agree, we can create an issue for it. Which can be solved first before we pick this one.

**Comment by singhvikash11** [comment]
@rahmatrhd @ravisuhag sounds good, let's create an issue to fetch policy details in the provider.

**Comment by rahmatrhd** [comment]
@singhvikash11 what I meant by fetching policy details is that from the UI, during appeal creation, we can fetch the policy once the resource is selected, from the policy details we can get the duration options

here's the changes required
1. add duration options in the `policy.appeal` config
2. move [AppealConfig](https://odpf.github.io/guardian/docs/reference/provider/#appealconfig) from provider config to policy config (can be done later, need to create separate issue)

final policy going to be like this:
```diff
  id: my-policy
  version: 1
  steps: []
+ appeal:
+   duration_options:
+   - name: 1 Day
+     value: 24h
+   - name: 2 Days
+     value: 48h
+   - name: Permanent
+     value: null # or "0h"?
+   allow_active_access_extension_in: 24h
-   allow_permanent_access: true # no longer needed since we already giving duration options
```

and from the provider config we can remove the `appeal` field

**Comment by singhvikash11** [comment]
@rahmatrhd we can add duration as part of the appeal however we should fetch policy as provider response itself to avoid one more API request from UI.

**Comment by ravisuhag** [comment]
@singhvikash11 I think it will be ok to add extra call. But we should keep provider and policy decoupled.

**Comment by rahmatrhd** [comment]
@ravisuhag @singhvikash11 another thing to note is we would be able to fetch policy after fetching provider bcs policy id is in the provider config. And another thing to do is to omit credentials (iam) from the policy details

**Comment by bsushmith** [comment]
Since we would not want to return iam credentials whenever policy API is called for appeal duration. We can take one of the below approaches - 

1. Remove the `iam` field from `GET policies/:id` endpoint
2. Add a new endpoint just to fetch the appeal options. something like - `GET policies/:id/appeal_options`
3. Add a query-param to the endpoint `GET policies/:id` to conditionally return `iam` credentials.

Option 2 feels better to me, given anything related to appeal configuration would be present in this field and it is more than enough.

wdyt @rahmatrhd @singhvikash11 @ravisuhag

**Comment by ravisuhag** [comment]
@bsushmith @rahmatrhd How would the flow work if there is more than one policy in Guardian. How would we decide which options to show when users create appeal?

**Comment by ravisuhag** [comment]
@bsushmith options 2 sounds good to me as well. But how about using endpoint as `GET policies/:id/aspects`. This would allow us to send all generic details of a policy in the future even other than appeal related if needed. Also can you add detail of how the response for this API would look like? cc @rahmatrhd

**Comment by bsushmith** [comment]
@ravisuhag  - this would be the actual endpoint with version number included - 
`/v1beta1/policies/{id}/versions/{version}/appeal_options`

As part of provider details, we would have `policy_id` and also `policy_version`. We will fetch appeal_options based on these values. 

sample request - 
```bash
curl --location --request GET 'localhost:3000/api/v1beta1/policies/policy_id_1/versions/25/appeal_options' \
--header 'Accept: application/json'
```

sample api response - 
```json
{
    "appeal": {
        "duration_options": [
            {
                "name": "1 Day",
                "value": "24h"
            },
            {
                "name": "3 Days",
                "value": "72h"
            },
            {
                "name": "Permanent",
                "value": "0h"
            }
        ]
    }
}


```


Changes included in Proton PR - https://github.com/odpf/proton/pull/166/files

---


> But how about using endpoint as GET policies/:id/aspects

Not sure about this. Makes sense but `aspects` is too generic, and may not translate as well as say `policies`

**Comment by ravisuhag** [comment]
@bsushmith Another option could be `preferences`.  Actually the idea is to make it generic. Basically, return all options related to a policy not just appeal specifically.

**Comment by rahmatrhd** [comment]
I think it'll be more ideal if policy details `/policies/:id/versions/:version` returns all the policy config except `iam.config` (because there's a credentials in it) and create another API for returning the iam with creds `/policies/:id/versions/:version/iam` but it'll require more changes

**Comment by ravisuhag** [comment]
@rahmatrhd @bsushmith In that case, lets actually make these changes and return it in get policy API only. @bsushmith wdyt?

**Comment by bsushmith** [comment]
I went with this approach so as not to interfere with the GET, PUT, and POST `policies` endpoint. They will return exactly what is expected of them based on REST API principles. We should not change that IMO. 

`GET /policies` will return `iam` and `appeal_options` also included in it, as PUT and POST also have this.

This new endpoint will enable users to query aspects of policy that might be required somewhere, without  credentials leak.

> Actually the idea is to make it generic. Basically, return all options related to a policy not just appeal specifically.

@ravisuhag  agreed on this.` preferences` or even `configurations` is fine by me.

**Comment by ravisuhag** [comment]
@bsushmith let's go with `preferences` in that case.
