### ISSUE TITLE
APIs for add and remove approver

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/guardian#229]
**Summary**
There is a case where the only approver is unavailable and the approval got blocked due to that. Need a way to add new approver to a pending appeal.

**Proposed solution**
- new API to add an approver
  `POST /appeals/{id}/approvals/{id_or_name}/approvers`
  body:
  ```json
  {
    "email": "new.approver@example.com"
  }
  ```
- new API to remove approver
  `DELETE /appeals/{id}/approvals/{id_or_name}/approvers/{email}`

**Comment by bsushmith** [comment]
@rahmatrhd What would happen when and if the only approver is removed? Is that step - marked as `auto-approved` ...

**Comment by rahmatrhd** [comment]
@bsushmith  if there's only one approver, that approver can't be removed. Added that validation as one of the task  in the PR's checklist
