### ISSUE TITLE
Issue with update of provider config field `AllowPermanentAccess`

### ISSUE THREAD

**Issue by bsushmith** [odpf/guardian#234]
**Description**

On update of provider, we use [merge](https://github.com/odpf/guardian/blob/main/core/provider/service.go#L178) of existing value in DB and new updated value, to autofill the empty values and take the latest provider value. 

If we have a provider record in DB with `Provider.Config.Appeal.AllowPermanentAccess` value as `true` already, and we update this field to `false` in new the updated provider record - because of the bug in the version of [mergo](https://github.com/imdario/mergo) that we use, the field will always remain `true` in DB.

mergo issue: https://github.com/imdario/mergo/issues/166

**To Reproduce**
* Insert a provider record in DB with `Provider.Config.Appeal.AllowPermanentAccess` value as `true`
* Update the same provider record with `Provider.Config.Appeal.AllowPermanentAccess` value as `false`
* Check the provider record; The value would still be `true` instead of `false`

**Expected behavior**
The field should be updated to whatever's the value in the latest provider record.

**Additional context**
* Version - `latest` main
* We use the same merge functionality for update resource also.
* Need to check if the latest version of [mergo](https://github.com/imdario/mergo) lib solves this, if not need to look for alternative fixes in code.

**Comment by bsushmith** [comment]
I see that this is not just for this `bool` field, but also for other fields.

Labels(`map[string]string`) are also merged instead of simple update and both `AllowPermanentAccess` and `AllowActiveAccessExtensionIn` are taken from existing provider values rather than the incoming update. 

Is this desired? If not, then, we should relook at how we use the `merge` library to autofill the missing values, and create our a provider struct manually for all fields taking in the new fields and also with default empty values for missing fields.

IMO, I don't think we should merge at all, we should be taking in the latest values always. 


wdyt @rahmatrhd @ravisuhag @singhvikash11

**Comment by mabdh** [comment]
If it is `PUT` API I think the expectation should be, it should update the entire record with the one pased in the API. If we desire to change partial fields in the record, that should be with `PATCH` API.
