### ISSUE TITLE
Ability to configure db connection settings

### ISSUE THREAD

**Issue by bsushmith** [odpf/guardian#245]
**Summary**
Ability to configure db connection settings while connecting to the database.

database/sql already supports some of these - 
https://pkg.go.dev/database/sql#DB.SetConnMaxLifetime
https://pkg.go.dev/database/sql#DB.SetMaxIdleConns
https://pkg.go.dev/database/sql#DB.SetMaxOpenConns
https://pkg.go.dev/database/sql#DB.SetMaxOpenConns

**Comment by ravisuhag** [comment]
This will be covered as part of removing gorm. #241
