### ISSUE TITLE
cron jobs are not getting triggered

### ISSUE THREAD

**Issue by bsushmith** [odpf/guardian#255]
**Description**
All cron jobs which are [enabled](https://github.com/odpf/guardian/blob/v0.3.0/internal/server/config.go#L23) by default, are not getting triggered properly. Out of the three in the server config, only the last one - `RevokeExpiredAppeals` is getting triggered. 

The issue occurs because in the [line](https://github.com/odpf/guardian/blob/v0.3.0/internal/server/server.go#L85), the code `return jobsMap[job.JobType](context.Background())` doesn't get evaluated thru the iteration and only happens at the end.
``` go
	for _, job := range enabledJobs {
		task := scheduler.Task{
			CronTab: job.Interval,
			Func:    func() error { return jobsMap[job.JobType](context.Background()) },
		}
		tasks = append(tasks, &task)
	}
```

**To Reproduce**
* Let all the cron jobs be enabled to run.
* Change the cron schedule for all three to be a very small interval - like every minute
* Run the server

The logs will show that only the `RevokeExpiredAppeals` job is getting triggered like below

```log
INFO[0000] server running on port: 3000                 
INFO[0039] running revoke expired appeals job       
INFO[0039] running revoke expired appeals job       
INFO[0039] running revoke expired appeals job       
^C
```

Ideally, all three jobs should get triggered, and the log should show something similar to - 
```log
INFO[0000] server running on port: 3000                 
INFO[0045] 🚨🚨🚨 running revoke expired appeals job       
INFO[0045] 🚨🚨🚨 running appeal expiration reminder job   
INFO[0045] 🚨🚨🚨 fetching resource...    
^C
```

**Expected behavior**
All three enabled jobs are expected to run, instead of only the last in the [enabled jobs](https://github.com/odpf/guardian/blob/v0.3.0/internal/server/server.go#L264) slice.

**Additional context**

Issue exists in versions - `v0.3.0`, `v0.3.1`, `v0.3.2`

**Comment by bsushmith** [comment]
The issue will get resolved if the code changes are done in the following way causing the `fn` to get evaluated in each iteration.
```go
	for _, job := range enabledJobs {
		fn := jobsMap[job.JobType]
		task := scheduler.Task{
			CronTab: job.Interval,
			Func:    func() error { return fn(context.Background()) },
		}
		tasks = append(tasks, &task)
	}
```

**Comment by rahmatrhd** [comment]
still couldn't understand why it was not working in an iteration but interesting! 😄
