### ISSUE TITLE
Collect usage history (access logs) data

### ISSUE THREAD

**Issue by mabdh** [odpf/guardian#265]
**Summary**
As part of #171 , one scope of access monitoring is from the provider access logs: `Analytics about what resources are being actually queried and how frequently`. We need to figure out how guardian utilize access usage history data for data access monitoring.

Some questions to help
1. How many times a resource is accessed
2. How many times sensitive resources are getting accessed 
3. Identify what operations are done on a resource (read/write)
4. Identify users with excess access rights (access that is active but is not used)

**Proposed solution**
1. Track access log to figure which user access what resource 
2. Check which providers that support usage history extraction
   - Bigquery
   - GCS
   - Gcloud IAM
   - Metabase
   - Tableau
   - Grafana
3. For provider that does not support access log (Expose APIs to submit access logs as well to help capture for providers which does not provide direct log extraction)
5. Labels for resources to mark as sensitive
6. Define generic data model

**Additional context**
This issue is concluded once these points are clearly answered
- Clarity on what providers that support usage history extraction and what doesn’t
- Generic data model on how the usage history/activities logs will be persisted in Guardian
- Approach on how to label a resource as sensitive
- Clear approaches on how to collect usage history
  - From provider that support usage history extraction
  - From provider that does not support usage history extraction
    - Exposed API to submit access logs

**Comment by rahmatrhd** [comment]
```go
type ProviderActivity struct {
	ID         string
	ProviderID string
	ResourceID string
	AccountID  string
	Timestamp  string
	// Action correlates with grant role/permissions
	Action string // read | write | ...
	// Type is specific to the provider. It defines what kind of activity is being run
	Type     string // query | view | export | etc...
	Metadata map[string]interface{}
}
```
I think this is how the activity log entity should looks like, at least
note: this is still the first proposal, might update this in the future
