### ISSUE TITLE
Automate access revocation in case of dormant account/invalid access/data exfiltration

### ISSUE THREAD

**Issue by mabdh** [odpf/guardian#266]
**Summary**
The bulk API revocation has been done here https://github.com/odpf/guardian/issues/202. However there is a still pending issue when we need to automate the revocation of an access that are under several conditions. 
e.g.
- Dormant account
- Invalid access
- Data exfiltration

**Proposed solution**
- Figure out what is the definition of dormant account
- Figure out conditions that are possible to do access auto revocation
- Approach on how to automate the revocation

**Comment by bsushmith** [comment]
@mabdh Please check this comment - https://github.com/odpf/guardian/issues/202#issuecomment-1188951709

We decided on this that - we'll let users decide how they will revoke the appeals and that they can use the bulk revoke appeals API to do so.

**Comment by mabdh** [comment]
Duplicate of #202
