### ISSUE TITLE
Migration script issue in v0.3.1

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/guardian#270]
**Description**
The migration script in [v0.3.1](https://github.com/odpf/guardian/releases/tag/v0.3.1) has an issue on backfilling the `permissions` column for prior appeals. The issue impacts appeals that have multiple roles to the same resource (from the same account_id as well), the backfilled `permissions` value might be incorrect (referencing to the other role instead of the designated role)

**To Reproduce**
1. update to v0.3.1
2. run migration
3. there will be some mismapped `role-permissions` from the backfill

**Expected behavior**
all `permissions` values mapping should be referenced to the right `role`

**Discussion**
1. How should we release this fix?
   - Option 1: merge the fix to `main` branch and create new latest release (`v0.3.6`)
      - pros: simpler way
      - cons: deployment that is still in the version before `v0.3.1` have to update to `v0.3.6` directly to avoid this bug
   - Option 2: create `v0.3.1-fix1` out of `v0.3.1` which only contains the fix
      - pros: user can skip `v0.3.1` and use `v0.3.1-fix1` instead. And user can still upgrade to the next versions sequentially (upgrading to `v0.3.2` after applying the fix won't cause an issue since the migration version is already marked to the latest migration script version)
      - cons: this strategy works for this case because the issue is related to the migration script. 
   - please share if you have any better strategy

**Comment by ravisuhag** [comment]
@rahmatrhd I think we should go with 0.3.6 which fixes the issues. As per semver guidelines as well, patch version is the right approach to resolve this.
