### ISSUE TITLE
Expose swagger UI

### ISSUE THREAD

**Issue by bsushmith** [odpf/guardian#271]
**Summary**
Expose swagger UI:
It would be helpful to interact with the guardian server through API way if there's a swagger UI exposed through the grpc-gateway. 

**Proposed solution**
How will it benefit CLI and its users? 
CLI already has a help command set to work with. This feature request is specifically to enhance the usage of the API way.

**Comment by ravisuhag** [comment]
This can be helpful in the dev and staging environments. But I think we should not expose this in a production environment. So, IMO it should be configurable.

**Comment by ravisuhag** [comment]
This can also be extracted as a package in salt to make it reusable.

**Comment by AkarshSatija** [comment]
Swagger UI can be hosted anywhere provided the swagger file is available. We should make that public in the repo and swagger UI can read it and render it. IMO It shouldn't be added to the application code.

**Comment by ravisuhag** [comment]
@AkarshSatija fair point. +1
