### ISSUE TITLE
Trim down duplicate approvers

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/guardian#275]
**Summary**
In some complex policy use cases, the returned approvers might be duplicated. Need to make the approvers list unique to avoid duplicate approvers as well as sending multiple notifications to the same user

**Proposed solution**
- During appeal creation, make the approver list unique before storing into db

**Comment by rahmatrhd** [comment]
approach:
need make the list unique after resolving the approvers list here https://github.com/odpf/guardian/blob/7f4eabe11f94144727ab24cb6f305b4ba4069f9d/core/appeal/service.go#L899-L944

**Comment by bsushmith** [comment]
@rahmatrhd When you mean duplicate approvers - Is it for the same approval step?

**Comment by rahmatrhd** [comment]
@bsushmith yes
