### ISSUE TITLE
refactor appeal functions

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/guardian#311]
proposing to refactor these items to improve code readability esp. in appeal and approval services

### create appeal
- https://github.com/odpf/guardian/blob/075f577dd0d1583a165917121f4517411bc8cf40/core/appeal/service.go#L909 move `appeal.Service.fillApprovals` to `domain.Appeal.InitApprovals(p domain.Policy) error`
- add `domain.Step.ToApproval(approvers []string) domain.Approval` to automatically convert list of approval step config to `domain.Approval`
- https://github.com/odpf/guardian/blob/075f577dd0d1583a165917121f4517411bc8cf40/core/appeal/service.go#L768 move `appeal.Service.resolveApprovers` to `domain.Step.ResolveApprovers(a domain.Appeal)`
- https://github.com/odpf/guardian/blob/075f577dd0d1583a165917121f4517411bc8cf40/core/appeal/service.go#L976 rename `appeal.Service.CreateAccess` to `appeal.Service.GrantAccessToProvider`
- add unit tests for methods in `domain.Appeal` and `domain.Approval`

### make action/update approval
- https://github.com/odpf/guardian/blob/075f577dd0d1583a165917121f4517411bc8cf40/core/appeal/service.go#L376 move `appeal.Service.MakeAction` to `approval.Service.UpdateApproval`

### approval. advance approval
- https://github.com/odpf/guardian/blob/075f577dd0d1583a165917121f4517411bc8cf40/core/approval/service.go#L50 move `approval.Service.AdvanceApproval` to `domain.Appeal.AdvanceApproval(p domain.Policy)`

**Comment by mabdh** [comment]
It looks like the changes are not really a major changes. Regardless I think it is a good start to refactor the codebase into odpf-like folder structure.

**Comment by rahmatrhd** [comment]
@mabdh what do you mean by odpf-like folder structure?

**Comment by mabdh** [comment]
@rahmatrhd what I meant was folder-structure of odpf standard 
similar with #199
