### ISSUE TITLE
Register Dataplex policy-tags as provider

### ISSUE THREAD

**Issue by singhvikash11** [odpf/guardian#319]
**Summary**
Register DataCatalog policy tags as a provider so users can raise requests for policy tags with `roles/datacatalog.categoryFineGrainedReader` permission

**Comment by ravisuhag** [comment]
@singhvikash11 can you describe in a bit more detail the use case for this? Also since the data catalog is part of dataplex now in google. How does that change this?

**Comment by singhvikash11** [comment]
Policy tags enable you to control who can view sensitive columns in BigQuery tables. In Data Catalog, you can add or remove policy tags to columns directly on the table entry details page.

Users that need access to columns protected with policy tags need the Fine-Grained Reader role. This role is assigned individually on every policy tag.

With this feature, the guardian will be able to register these policy tags as resources and users able to raise an appeal with the Fine-Grained Reader role to get access to secure columns. 

@ravisuhag There will be no change on policy-tag given this is part of dataplex now, anything else you want me to clarify?

**Comment by ravisuhag** [comment]
@singhvikash11 given data catalog is part of dataplex now, lets rename this provider to dataplex.

**Comment by ravisuhag** [comment]
@rahmatrhd @singhvikash11 Given it is still access to bigquery resources, should this be part of bigquery provider itself? Can you elaborate on what will be the resources in this provider?

**Comment by singhvikash11** [comment]
@ravisuhag this will enable to access policy tags in dataplex and for column-level access users or custom-job need to assign these tags to columns on table metadata API. 

@ravisuhag policy tags can enable column access on bigquery but edit table-metadata with policy tags is not in scope of this pr. WDYT?

**Comment by ravisuhag** [comment]
@singhvikash11 yes, agree.
