### ISSUE TITLE
Add authentication to guardian using google idtoken (from google SSO login)

### ISSUE THREAD

**Issue by swallowstalker** [odpf/guardian#350]
**Summary**

Right now, I saw that the only way to know which user did some action is by using `AUTHENTICATED_USER_HEADER_KEY` or `X-Auth-Email` request header (default). It seems that anyone could just change the email on request header to act as someone who create appeal/approve request. On my project, I need to add some kind of auth mechanism to make sure that the request is coming from legitimate user (in my case, user which is logged-in via Google SSO)

**Proposed solution**

Adding new interceptor for authentication using google's idtoken. If you have a frontend dashboard which has login via Google feature, you could integrate it with Guardian.

There will be configuration to enable/disable this auth interceptor, and if idtoken validation is disabled, it will fallback to default auth checking using `X-Auth-Email` request header

Related pull request: https://github.com/odpf/guardian/pull/349

**Comment by rahmatrhd** [comment]
The existing guardian is intended to be served behind an auth service/proxy such as [shield](https://github.com/odpf/shield) or [Google IAP](https://cloud.google.com/iap) and not to be directly consumed by the client. Therefore, the current approach is considering any value from the header (`AUTHENTICATED_USER_HEADER_KEY`) as a legitimate user email **provided by the auth service**, not client. 

Although I agree that your use case is valid and common, it also should be introduced into guardian as a configurable approach e.g.: the authentication method can be configured through `config.yaml` whether to use header key, SSO login, or any other supported method.

Any suggestions @ravisuhag @bsushmith @haveiss?

**Comment by swallowstalker** [comment]
I see your point, thanks for pointing that out. I wasn't aware that guardian should be behind IAP, but let's say that I'm going to deploy it without IAP or shield, is there any security precaution that I should consider when using guardian features and I only use the google idtoken interceptor?

> Although I agree that your use case is valid and common, it also should be introduced into guardian as a configurable approach e.g.: the authentication method can be configured through config.yaml whether to use header key, SSO login, or any other supported method.

I'm open to any suggestions about the configuration 👀

**Comment by ravisuhag** [comment]
I agree with suggestion from @rahmatrhd . @swallowstalker Actually, not just Guardian most of our services expect Shield or any other auth mechanism to be placed in front. But, idea of having an optional auth system within tools completely makes sense. My proposal would be move auth interceptor in a single place in https://github.com/odpf/salt or Shield to make it reusable. If using salt we can introduce a auth package which can then be used Guardian and should be made optional as Rahmat suggested.

**Comment by swallowstalker** [comment]
would that be ok if i move the interceptor code to `github.com/odpf/salt/auth/grpc/idtoken.go`, and then import it on `internal/server/server.go` just like this PR? do I need to change the config.yaml structure?

**Comment by ravisuhag** [comment]
@swallowstalker Instead of moving it right away in salt. Let's create an `auth` package in `github.com/odpf/guardian/pkg/` which can then later be easily moved to salt. 

Also, now that we are moving towards introducing different ways to establish the identity of users we should generalize the configs. 
Something like:
```
auth:
 provider: default/google
 options: 
```
and in auth package, we can have a generic interface that each provider should meet.  Thoughts? 
cc @rahmatrhd @bsushmith @AkarshSatija

**Comment by ravisuhag** [comment]
A reference for anyone checking this issue: https://github.com/salrashid123/google_id_token

**Comment by swallowstalker** [comment]
> @swallowstalker Instead of moving it right away in salt. Let's create an auth package in github.com/odpf/guardian/pkg/ which can then later be easily moved to salt.

Agree, I will move interceptor code into pkg dir

Maybe we can have structure like this?
```
auth:
 provider: default/google/oidc
 options: 
  oidc:
   audience:
   eligible_email_domains:
```

default has no additional config at all, how about that?

**Comment by ravisuhag** [comment]
@swallowstalker We would need to pull out `AUTHENTICATED_USER_HEADER_KEY ` also in this. Which i think could be part of default auth provider.

**Comment by swallowstalker** [comment]
so it would be something like this?

```
auth:
 provider: default/google/oidc
 options: 
  default:
   authenticated_user_header_key:
  oidc:
   audience:
   eligible_email_domains:
```

**Comment by ravisuhag** [comment]
Yes

**Comment by rahmatrhd** [comment]
```yaml
auth:
  provider: default
  default:
    header_key: 
```

```yaml
auth:
  provider: oidc
  oidc:
    audience:
    eligible_email_domains:
```

^ these look simpler IMO

**Comment by ravisuhag** [comment]
```
auth:
 provider: default/google/oidc
 options: 
   audience:
   eligible_email_domains:
```
I think keeping the options key makes it easy to identify that these are the provider options. But we can omit the low-level provider key. Thoughts? If we see challenges with this approach even what Rahmat is proposing should be good as well.

**Comment by swallowstalker** [comment]
I'm leaning towards @rahmatrhd idea, because i thought that specifying the provider type on the config will give less empty valued-fields on the implementation struct. If we choose default, i think it's better to have `oidc` entire config value to nil, and vice versa, rather than having 1 options struct with multiple empty fields (imo)

```
type AuthConfig struct {
  Provider string `mapstructure:"provider"`
  Default DefaultConfig `mapstructure:"default"` # this will be nil if we choose oidc, or
  Oidc OidcConfig `mapstructure:"oidc"` # this will be nil if we choose default
}

type DefaultConfig struct {
  HeaderKey string `mapstructure:"header_key"`
}

type OidcConfig struct {
  Audience string `mapstructure:"audience"`
  EligibleEmailDomains string `mapstructure:"eligible_email_domains"`
}
```

instead of 

```
type AuthConfig struct {
  Provider string `mapstructure:"provider"`
  Options AuthOptions `mapstructure:"options"`
}

type AuthOptions struct {
  HeaderKey string `mapstructure:"header_key"` # this will be empty if oidc is chosen
  Audience string `mapstructure:"audience"` # this will be empty if default is chosen
  EligibleEmailDomains string `mapstructure:"eligible_email_domains"` # this will be empty if default is chosen
}
```

**Comment by ravisuhag** [comment]
Sounds good . Let's go with it.

**Comment by swallowstalker** [comment]
hi all, i've refactored auth interceptor into pkg/auth package, but i'm still wondering about how to support backward compatibility for `AUTHENTICATED_USER_HEADER_KEY`

here's my attempt to support previous version without making anyone break their old config when upgrading guardian to latest version, what are your thoughts on this?

https://github.com/odpf/guardian/pull/349/commits/5149a63c14d794d6d1019aedd7ab73cc6a2b1f4d

**Comment by ravisuhag** [comment]
> hi all, i've refactored auth interceptor into pkg/auth package, but i'm still wondering about how to support backward compatibility for `AUTHENTICATED_USER_HEADER_KEY`
> 
> here's my attempt to support previous version without making anyone break their old config when upgrading guardian to latest version, what are your thoughts on this?
> 
> [5149a63](https://github.com/odpf/guardian/commit/5149a63c14d794d6d1019aedd7ab73cc6a2b1f4d)

@swallowstalker This is fine.

**Comment by rahmatrhd** [comment]
adding this as part of [v0.6.0](https://github.com/odpf/guardian/milestone/7) milestone

**Comment by rahmatrhd** [comment]
closing this as https://github.com/odpf/guardian/pull/349 has been merged
