### ISSUE TITLE
Add API to assign/update owner of a grant

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/guardian#362]
### Problem
With the recent [Import Grants](https://github.com/odpf/guardian/issues/206) feature, the default value for non-human access grants' `owner` field is empty. This is because Guardian can't determine the owner of the imported grants except for human accounts (individual email).

### Requirements
- Ability to assign a new owner to grants with empty owner
- Ability to replace the existing owner

### Proposed solution
1. Add API for updating grant's owner
   `PUT /grants/:id/owners` with request body: `{ "account_id": "user@example.com" }`
2. Add generic update grant API (preferred)
   `PATCH /grants/:id` with request body: `{ "owner": "user@example.com" }`
   - only allow field `owner`

#### Checklist
- [ ] Validate the owner value should not be empty
- [ ] Send notification to the new owner
- [ ] Send notification to the previous owner (if any)
- [ ] Record in audit log

### Next:
1. Introduce `co-owners: []string` field into Grant. An access/grant can be owned by multiple people especially if it's a service account or group access. `co-owners` will receive notifications like expiring notif and revocation notif the same way as the original owner.

**Comment by rahmatrhd** [comment]
@ravisuhag @haveiss @mabdh @bsushmith requesting for your comments 🙏

**Comment by bsushmith** [comment]
This feature will also help us in assigning a new owner in case the previous owner is not part of the organization. 
For example, we see for serviceAccounts, the previous owners are no longer in the org, and then nobody gets any reminders when the particular serviceAccount access will expire.

**Comment by rahmatrhd** [comment]
> Would it be possible to remove owners also? In case somebody wants to re-assign their ownership and does not want to be notified about it?

Grants should have owner(s) unless it is undeterminable (like in ImportGrants). If a user doesn't want to receive notifications about certain grants, they should hand them over to someone else.

> In the proposed options - I feel option2 might lead to abuse as people might use this to update other fields even if they are not intended to be.

this API should only work on **allowed** fields. For now, I think it'll be only `owner`, later after we introduced `co-owners` we can also add them.

**Comment by bsushmith** [comment]
> Grants should have owner(s) unless it is undeterminable (like in ImportGrants). If a user doesn't want to receive notifications about certain grants, they should hand them over to someone else.

Yes. Agreed. I meant in a manner of - 
Could we have similar restrictions in the way we add/remove approvers for a given step. We check to ensure at least one approver is present in case of removal. We should be able to do that here also.

**Comment by mabdh** [comment]
Yeah, I feel the 2nd solution is simpler. But do we need to restrict the caller of the API? So not all people could update the owner field.

For the next `co-owners: []string`, I am not sure if it is that scalable to do so, but I think that could be discussed later.

**Comment by rahmatrhd** [comment]
> But do we need to restrict the caller of the API?

@mabdh the API restriction will be done from the auth proxy (shield) only, as right now that's how we configure superadmin privileged APIs as well

**Comment by rahmatrhd** [comment]
@bsushmith @mabdh can we sign off on the preferred approach? if so I'll work on this soon

**Comment by bsushmith** [comment]
Agreed on the second approach with restrictions on what can be updated. 👍
