### ISSUE TITLE
Fetch labels for bigquery dataset/table

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/guardian#372]
**Summary**
BigQuery dataset/table has some metadata that hasn't been fetched into guardian resource details. We want to fetch them and store them in the resource details for some use case such as determining the dataset/table owner and pii flag

**Proposed solution**
add metadata field within `details`:
```diff
// resource
{
  "id": "",
  ...
  "details": {
+    "metadata": {
+      "labels": {
+        "key": "value"
+      },
+.     "other_metadata": ""
+    }
  }
}
```

Other requirements:
- In the updateResource API, `metadata` field should not be updateable by the user. It only can be updated from FetchResource

**Comment by bsushmith** [comment]
@rahmatrhd couple of questions on this - 
1. Will this fetch all labels for a bigquery dataset/table or only specific configurable labels only? 
2. Is this specific to only bigquery resources?

**Comment by rahmatrhd** [comment]
@bsushmith
1. It should fetch all labels (no configuration needed)
2. For this, I'm setting the scope only for bq resources. If we later need to add metadata for other provider resources, maybe having a dedicated `metadata` column would be better
