### ISSUE TITLE
Migrate logging to use odpf/salt

### ISSUE THREAD

**Issue by ravisuhag** [odpf/guardian#39]
Use salt logger for logging in Guardian. 

https://github.com/odpf/salt/log

**Comment by wisdommatt** [comment]
I would like to work on this.

@ravisuhag github.com/odpf/salt/log has different loggers: Zap & Logrus, which one should i use to replace the current guardian logger ?

**Comment by ravisuhag** [comment]
@wisdommatt You can use Logrus. For reference implementation please take a look at https://github.com/odpf/meteor
Thanks for your contribution, assigning this to you.

**Comment by ravisuhag** [comment]
@wisdommatt Thanks, added some comments.

**Comment by wisdommatt** [comment]
> @wisdommatt Thanks, added some comments.

Okay i will do that right away
