### ISSUE TITLE
Add Audit Logging

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/guardian#72]
## Requirements
- track activities related to data changes & audit logs

## Proposed solution
Create a new table in db to store audit logs as well as create its repository and service. Audit Service will be used across other services to log the activity.

#### database model
```go
type AuditLog struct {
	Timestamp  time.Time
	Action     string // example: appeal.created, provider.created, provider.updated, etc.
	Actor      string // example: user@example.com or system
	Data       interface{}
	Metadata   interface{}
}
```
#### implementation
1. repository
implementation of this interface can be created in `salt` for reusability.
```go
type AuditRepository interface {
	List(filters map[string]interface{}) ([]*AuditLog, error)
	Create(*AuditLog) error
	BulkCreate([]*AuditLog) error
}
```
2. guardian's audit service
```go
type AuditAction string // typed audit action
var (
	ProviderCreated     AuditAction = "provider.created"
	ResourceBulkCreated AuditAction = "resource.bulkCreated"
	// ...
)

// typed audit data for each audit action
type ProviderCreatedData domain.Provider
type ResourceBulkCreatedData struct {
	CreatedResourceIDs []string
	RemovedResourceIDs []string
}

// audit service interface representation
type AuditService interface {
        Log(actor, action, message string, payload interface{}) error
}

// usage
auditService.Log("user@example.com", audit.ProviderCreated, "message example", audit.ProviderCreatedData{...})
auditService.Log("system", audit.ResourceBulkCreated, "message example", audit.ResourceBulkCreatedData{...})
```

### guardian audit log list
Domain | Action | Actor | Payload
-- | -- | -- | --
provider | create | authorized user | Provider
provider | update | authorized user | Provider
policy | create | authorized user | Policy
resource | bulk insert | guardian | created resource IDs, (soft) deleted resource IDs
resource | update | authorized user | Resource
appeal | create | authorized user | Appeal
appeal | cancel | authorized user | -
appeal | approve | authorized user | -
appeal | reject | authorized user | appeal id, reason
appeal | revoke | authorized user | appeal id, reason
appeal | automated revoke | guardian | -
appeal | extend | authorized user | Appeal
approval | approve | authorized user | approval name, appeal id
approval | automated approve | guardian | approval name, appeal id
approval | reject | authorized user | approval name, appeal id
approval | automated reject | guardian | approval name, appeal id

**Comment by ravisuhag** [comment]
@rahmatrhd We should also consider Audit service to be extensible in storage. Audit could be stored in database, can also be sent to kafka as an event in future.

**Comment by mabdh** [comment]
This looks good.

I have 1 suggestion but not sure it will be over-optimized or not, regardless we might need this in the future.

How about we introduce namespacing in the audit itself?

**DB Model**
```
type AuditEvent struct {
	Timestamp time.Time
        Namespace string
	Action    string // example: appeal:create, provider.create, provider.update, etc.
	Actor     string // example: user@example.com or system
	Payload   interface{}
}
```

**Usage**
```
auditService.Log(actor, namespace, action, payload)
auditService.Log("user@example.com", "policy", "create", &domain.Policy{...})
auditService.Log("system", "appeal", "revoke", nil)
```

**Comment by ravisuhag** [comment]
@rahmatrhd Also check this blog. https://www.enterpriseready.io/features/audit-log/
Some nice suggestions.

**Comment by ravisuhag** [comment]
One more thing, i think payload could be called message.

**Comment by rahmatrhd** [comment]
> @mabdh How about we introduce namespacing in the audit itself?
was also thinking the same, but wanted to keep it simple, and we can still have a convention in the action name itself to have namespacing anyway

> @ravisuhag One more thing, i think payload could be called message.
payload here is more for JSON data for later queries. How about having both payload and message (string)?

**Comment by ravisuhag** [comment]
In that case data could be beter. Payload seems very specific to request. WDYT?

**Comment by StewartJingga** [comment]
Minor concern,`AuditEvent` sounds like an Audit process which does not represent what we are storing.
From what I am seeing, we are storing more of list of item/actions/logs to be audited.
This looks like more of a UserLog/UserAction which in the end will be used for auditing.
I'm still okay if we are going with `AuditEvent` if that is what we have been calling.

Also should we just make `data` as `map[string]interface{}` instead if it is always gonna be a map? @rahmatrhd

**Comment by StewartJingga** [comment]
> @rahmatrhd Also check this blog. https://www.enterpriseready.io/features/audit-log/ and google audit proto. https://github.com/googleapis/googleapis/blob/master/google/cloud/audit/audit_log.proto Some nice suggestions.

Just read this, `AuditLog` seems more representative of what we are storing rather than `AuditEvent`. wdyt? @rahmatrhd @ravisuhag

**Comment by rahmatrhd** [comment]
> Also should we just make data as map[string]interface{} instead if it is always gonna be a map? @rahmatrhd

@StewartJingga one reason I was not limiting `data` to `map[string]interface{}` is because JSON value could be a single string, integer, or array as well.

**Comment by rahmatrhd** [comment]
description updated.
updates:
1. renamed action names to use past tense e.g. `provider.created` etc.
2. renamed `payload` to `data`
3. added `message` field
4. added implementation details

@ravisuhag @StewartJingga @mabdh

**Comment by rahmatrhd** [comment]
changing the model on today's discussion when reviewing https://github.com/odpf/salt/pull/32 with @krtkvrm 
```diff
type AuditLog struct {
	Timestamp  time.Time
	Action     string
	Actor      string
-	App       struct {
-	        Name    string
-	        Version string
-       }
	Data       interface{}
	Metadata   interface{}
}
```

1. information such as app name, app version, and trace id should be part of `metadata` itself
